workflows:
  debug-build:
    name: Debug Build Workflow (Android + iOS)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.22.3
      xcode: latest
      java: 17
      groups:
        - mygroup
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Get flavor based on branch
        script: |
          CURRENT_BRANCH=${CM_BRANCH}
          if [[ "$CURRENT_BRANCH" == "master" ]]; then
            FLAVOR="production"
          elif [[ "$CURRENT_BRANCH" == "staging" ]]; then
            FLAVOR="staging"
          else
            FLAVOR="development"
          fi
          echo "FLAVOR=$FLAVOR" >> $CM_ENV
          echo "Building for flavor: $FLAVOR"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Decode keystore from environment variable
        script: |
          mkdir -p $HOME/.keystore
          echo $KEYSTORE_BASE64 | base64 --decode > $HOME/.keystore/upload-keystore.jks

      - name: Create signing config
        script: |
          cat >> android/key.properties <<EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=$HOME/.keystore/upload-keystore.jks
          EOF

      - name: Analyze project (optional)
        script: flutter analyze
        ignore_failure: true

      - name: Build signed APK (Debug)
        script: |
          flutter build apk --debug --flavor $FLAVOR -t lib/main_${FLAVOR}.dart

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS App (Debug)
        script: |
          flutter build ios --debug --no-codesign --flavor $FLAVOR -t lib/main_${FLAVOR}.dart

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - sujithks.ks7@gmail.com
