workflows:
  debug-build:
    name: Debug Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: 3.22.3
      xcode: latest
      java: 17
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Setup local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Flutter analyze
        script: flutter analyze
        ignore_failure: true
      
      - name: Build APK (debug)
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
