name: Version Check

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Get the last version from git tags
        id: get_last_version_tag
        run: |
          # Determine the target branch of the pull request
          branch_name="${{ github.base_ref }}"

          echo "Branch name: $branch_name"

          # Get all tags sorted by creation date
          all_tags=$(git tag --sort=-creatordate)

          # Find the last tag in all tags 
          last_version_tag=$(echo "$all_tags" | grep -oP '(?<=v)\d+\.\d+\.\d+.*' | head -n 1)

          echo "Last version tag: $last_version_tag"


          echo "Extracted last tag version: $last_version_tag"

          # Export the last version for use in later steps
          echo "last_version_tag=$last_version_tag" >> $GITHUB_ENV



      - name: Read current version from pubspec.yaml
        id: read_pubspec
        run: |
          current_version=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "current_version=$current_version" >> $GITHUB_ENV
          
          echo "Current version: $current_version"

      - name: Compare versions
        id: compare_versions
        run: |
          last_version_tag="${{ env.last_version_tag }}"
          current_version="${{ env.current_version }}"
          
          # current version is not the same as the last version, so finish the workflow
          if [[ "$last_version_tag" != "$current_version" ]]; then
            echo "Versions are different: $last_version_tag != $current_version"
            exit 1
          fi

          echo "Versions are the same: $last_version_tag == $current_version"
